### ISSUE TITLE
Quick error fix + new issue running

### ISSUE THREAD

**Issue by michaelmurfy** [ZAP-Quebec/unifi-adoption-bot#1]
Heya,

Didn't want to create a pull request for a simple change however just spotted an error in `unifi.js`:
`this pass = pass;` should potentially be `this.pass = pass;`.

Also when running I am getting the following:
```
/usr/local/lib/node_modules/unifi-adoption-bot/node_modules/async/dist/async.js:840
        if (fn === null) throw new Error('Callback was already called.');
                         ^

Error: Callback was already called.
    at /usr/local/lib/node_modules/unifi-adoption-bot/node_modules/async/dist/async.js:840:32
    at /usr/local/lib/node_modules/unifi-adoption-bot/node_modules/async/dist/async.js:4956:25
    at apply (/usr/local/lib/node_modules/unifi-adoption-bot/node_modules/async/dist/async.js:21:25)
    at /usr/local/lib/node_modules/unifi-adoption-bot/node_modules/async/dist/async.js:56:12
    at Request.<anonymous> (/usr/local/lib/node_modules/unifi-adoption-bot/node_modules/node-unifi/unifi.js:1099:11)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/unifi-adoption-bot/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
```
I am likely jumping on this project too early since it is perfect for my needs but you able to give me any quick pointers on what I am doing wrong?

Cheers.

**Comment by JeanSebTr** [comment]
Hi,

it's indeed early, I was publishing small improvement to deploy on our server. The typo slipped through a few versions. I just published 0.0.7 with the fix.

The only thing I can guess from the stack trace, it is that a request did not work. What are the logs around the error ? That's possible that there's not much to help yet, I'll add more useful logs with a proper verbosity flag.

Does your controller run on the default ports ?


Anyway, I'm glad it can be useful to someone else, don't hesitate to report other issues you might have or improvement idea that could be helpful.

**Comment by JeanSebTr** [comment]
@michaelmurfy just published 0.0.9 with better logs.

Let me know if that helps or paste more logs here with `-v debug`.

**Comment by michaelmurfy** [comment]
I've had assistance from a friend - Just a further minor bug fixed in #2:

Use `console.warn` instead on line 69 of `index.js`
````
Use caution when passing password with the command line's arguments
debug: Create API object with url https://unifi_controller:8443
verbose: Calling api: login
verbose: Successfully called login
info: Successfully connected to unifi controller
````
Thanks very much for making a useful script! Just need to wait to see if it actually works with my controller now.

**Comment by michaelmurfy** [comment]
Also you may want to update the `readme.md` file to list the logging levels needed to make it work. I've got it all figured out now after reading what the code was looking for but it is working well with my controller - more for other people who may want to give this a go.
